# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-be6b0033-9698-49a4-b072-3fe1cde14669";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-be6b0033-9698-49a4-b072-3fe1cde14669".device = "/dev/disk/by-uuid/be6b0033-9698-49a4-b072-3fe1cde14669";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-be6b0033-9698-49a4-b072-3fe1cde14669";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-be6b0033-9698-49a4-b072-3fe1cde14669";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
